steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - service
      - "-f"
      - service/Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--update-env-vars"
      - "AUTHEN=$_AUTHEN,COOKIE=$_COOKIE,API=$_API,USER=$_USER"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: asia-southeast1
  _LABELS: gcb-trigger-id=9a8b603d-e308-480f-bc69-2381b44f2141
  _TRIGGER_ID: 9a8b603d-e308-480f-bc69-2381b44f2141
  _GCR_HOSTNAME: asia.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: kopihub-service
  _AUTHEN: "TGS eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjYWxsZXIiOiJsb2dpYy1jbGllbnQiLCJhZGRyZXNzIjowLCJzaG9wX2lkIjo5MjU3LCJhcHBfdHlwZSI6MiwidWlkIjoyMTA2OSwiY2xpZW50X3R5cGUiOjUxMiwiZXhwIjoxNjA1MzMxMzM0LCJkZXZpY2VfaWQiOjIzNTAzfQ.tYIDDy1Qxqa-Dc4YHUCgfuhTemr91cEGmovsB_ohrOiluyE1zaU32PviKg-RMas74h5aUmCB4kYWaFtSTJKoljXf-awQLIPu2tVOIP3TtZahABFJlqqcqfqEEEKoZ-ETCNDKLnfZiVTJMJ_K5Fy2-5j31S1ovsKhgiyjMdbvj4iclkInHtqOaGndhdr43FEq9YJIFoTVAawPsy3BBlH3Jh9QvhCAsKLQJQXusdDHWy3-hzVK690_7KH-eGEOhYnJLW_-h6VGoNWoknwU3qQ_S_aluxM-7dKAUctomRZPrRkGkBl8FFF-96l1WGvrWYXH5Kn2kAW4Np-spAfdFijjwg"
  _COOKIE: "__utma=21896485.1099646837.1605266724.1605266724.1605266724.1; __utmc=21896485; __utmz=21896485.1605266724.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.3.1099646837.1605266724; _gid=GA1.3.768779968.1605266724; _fbp=fb.2.1605266724190.189167266; posocha=MTYwNTI2Njg3MXxOd3dBTkVkTlJsZFdVbFZXVlVaUVRVSkVSa2RQUjB4SU1qSlFVRXMwUVVnM1VEUTFWMEZJUzAxSFMwNDBVVkJQTmtWSk5VVlJVRkU9fKPPkfV3XLdR3DAIP9OpQLiu_jUzpEyEh5vxtUZ2x1oH; _gat_gtag_UA_91617479_7=1"
  _API: "https://kopihub-api-ura2vr67wa-as.a.run.app/graphql"
  _USER: "368137c3-c961-4eeb-81c3-cabab70ae9f8"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - kopihub-service
