steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - service
      - "-f"
      - service/Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--update-env-vars"
      - "AUTHEN=$_AUTHEN,COOKIE=$_COOKIE,API=$_API,USER=$_USER"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: asia-southeast1
  _LABELS: gcb-trigger-id=9a8b603d-e308-480f-bc69-2381b44f2141
  _TRIGGER_ID: 9a8b603d-e308-480f-bc69-2381b44f2141
  _GCR_HOSTNAME: asia.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: kopihub-service
  _AUTHEN: "TGS eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjYWxsZXIiOiJsb2dpYy1jbGllbnQiLCJhZGRyZXNzIjowLCJzaG9wX2lkIjo5MjU3LCJhcHBfdHlwZSI6MiwidWlkIjoyMTA2OSwiY2xpZW50X3R5cGUiOjUxMiwiZXhwIjoxNjA1OTM5OTQ0LCJkZXZpY2VfaWQiOjIzNTAzfQ.gyIrTW0gE9r-0QCLkCxjwdU06LaUS_6Ne314DzilWswlJD3qlOEZRI-efEE_QYFSkuWaFR_aIf3IE3qJxfWu-DpHr1qz-ngH8pp192P5ugwPqA0r2Ir4yTOgZHbf4KAomH2m6TDhQBgX7thfSjXhLcecFC9rGetw7K9_ndZQl0ACPiFjMyCLsx5CsEKSd2jYATjD4teq_tTupid8by0fr1ysORlEvBwbPC27lwHoCt8xV9jVY2HTEez0OPicQfpzIg2jQL6BSh-9FpvVEJjo7cLOk9RYmjf4xGnX7Vbe7qvdoTopuL7RosGJ-E4odGoQtY3aQIPGurSgQV3h68KH4A"
  _COOKIE: "__utma=21896485.621032673.1605928903.1605928903.1605928903.1; __utmb=21896485.0.10.1605928903; __utmc=21896485; __utmz=21896485.1605928903.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.3.621032673.1605928903; _gid=GA1.3.900473845.1605928903; _fbp=fb.2.1605928906548.60953752; posocha=MTYwNTkyOTE0NHxOd3dBTkZOVFNqUllWMFZhUzA1RVJ6TXlVakpRUkVKUU0xZFlVVE5PTkZsUVYxVlpTMWhEUnpKSFZGWmFUMUJFVkRaRVZqTklXRUU9fLSLQZ49PkJ5LUyRqCj-5L7iroiiJpYhfusuHmjHd486; _gat_gtag_UA_91617479_7=1"
  _API: "https://kopihub-api-ura2vr67wa-as.a.run.app/graphql"
  _USER: "368137c3-c961-4eeb-81c3-cabab70ae9f8"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - kopihub-service
